name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Node.js 버전을 지정하세요

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run lint
      - name: Run ESLint
        run: npm run lint

      # 5. Build the project
      - name: Build project
        run: npm run build
